db:
  url: jdbc:mysql://root:E2-3HaF6Fc-c4GDeh--faA42D113CAa3@monorail.proxy.rlwy.net:56791/vortex
  username: root
  password: E2-3HaF6Fc-c4GDeh--faA42D113CAa3
  email: vortexgames19922024@gmail.com
  passwordEmail: mipb ezcg ejco smxk

